### ISSUE TITLE
Not taking SENTRY_ORG or SENTRY_PROJECT from environment variables

### ISSUE THREAD

**Issue by ricokahler** [getsentry/sentry-netlify-build-plugin#10]
![image](https://user-images.githubusercontent.com/10551026/83290302-71950c00-a1b4-11ea-93df-9b183038985e.png)

However the current readme says I can use environment variables instead:

>  You can also use [site environment variables](https://docs.netlify.com/configure-builds/environment-variables/) to configure these values:
> | name | description | default |
> |------|-------------|---------|
> | `SENTRY_AUTH_TOKEN` | Authentication token for Sentry. | - |
> | `SENTRY_ORG` | The slug of the organization name in Sentry. | - |
> | `SENTRY_PROJECT` | The slug of the project name in Sentry. | - |

Is this a mistake or are those options required?

I apologize if i missed anything! Thanks for this cool build plugin!

**Comment by jonesphillip** [comment]
@ricokahler that issue has been solved in version 1.0.3 which is now live. Please give it a go again, sorry about that!

**Comment by ricokahler** [comment]
It's still not working for me.

![image](https://user-images.githubusercontent.com/10551026/83306949-8d5adb00-a1d1-11ea-8266-4b46e88bace9.png)

It says "project not found". This may be a misconfiguration on my end. The docs say to use the "The slug of the project name in Sentry."

However, I don't see a slug, I only see an ID as part of a query param. Is this the value I was using for `SENTRY_PROEJCT`.

![image](https://user-images.githubusercontent.com/10551026/83307070-cc892c00-a1d1-11ea-902e-37d774b97fc6.png)

Is that the correct value?

**Comment by jonesphillip** [comment]
@ricokahler ah you'll want the project-slug not the project id. In the example below, your project slug would be "authentication-service" or "c". Let me know if that works for you
![Screen Shot 2020-05-29 at 2 31 29 PM](https://user-images.githubusercontent.com/7978631/83307227-19acd400-a1b9-11ea-9e16-1b16b1207621.png)
